
# Force dep to vendor the code generators, which aren't imported just used at dev time.
# Picking a subpackage with Go code won't be necessary once https://github.com/golang/dep/pull/1545 is merged.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.4"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.4"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.4"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.4"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.4"

[[override]]
  name = "github.com/percona/mongodb-orchestration-tools"
  revision = "234bd1c80d7db907643b132a36740040c44a28b6"

[[override]]
  branch = "master"
  name = "golang.org/x/crypto"

[[override]]
  branch = "master"
  name = "golang.org/x/net"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false
    unused-packages = false

  [[prune.project]]
    name = "github.com/percona/mongodb-orchestration-tools"
    non-go = false
    unused-packages = false

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  version = "=v0.0.7"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
